import { Artwork } from '@/types/artwork'

export const artworks: Artwork[] = [
  // 분류 1-16: Camino 길 위의 풍경
  { id: 1, title: 'Artwork 1', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/1.jpg', category: 'Camino 길 위의 풍경' },
  { id: 2, title: 'Artwork 2', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/2.jpg', category: 'Camino 길 위의 풍경' },
  { id: 3, title: 'Artwork 3', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/3.jpg', category: 'Camino 길 위의 풍경' },
  { id: 4, title: 'Artwork 4', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/4.jpg', category: 'Camino 길 위의 풍경' },
  { id: 5, title: 'Artwork 5', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/5.jpg', category: 'Camino 길 위의 풍경' },
  { id: 6, title: 'Artwork 6', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/6.jpg', category: 'Camino 길 위의 풍경' },
  { id: 7, title: 'Artwork 7', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/7.jpg', category: 'Camino 길 위의 풍경' },
  { id: 8, title: 'Artwork 8', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/8.jpg', category: 'Camino 길 위의 풍경' },
  { id: 9, title: 'Artwork 9', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/9..jpg', category: 'Camino 길 위의 풍경' },
  { id: 10, title: 'Artwork 10', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/10.jpeg', category: 'Camino 길 위의 풍경' },
  { id: 11, title: 'Artwork 11', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/11 .jpg', category: 'Camino 길 위의 풍경' },
  { id: 12, title: 'Artwork 12', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/12.jpg', category: 'Camino 길 위의 풍경' },
  { id: 15, title: 'Artwork 15', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/15.jpg', category: 'Camino 길 위의 풍경' },
  { id: 16, title: 'Artwork 16', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/16.jpg', category: 'Camino 길 위의 풍경' },

  // 분류 17-34: 무우국(國) 미나리(里)의 사계
  { id: 17, title: 'Artwork 17', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/17.jpg', category: '무우국(國) 미나리(里)의 사계' },
  { id: 18, title: 'Artwork 18', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/18.jpg', category: '무우국(國) 미나리(里)의 사계' },
  { id: 19, title: 'Artwork 19', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/19.jpg', category: '무우국(國) 미나리(里)의 사계' },
  { id: 20, title: 'Artwork 20', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/20.jpg', category: '무우국(國) 미나리(里)의 사계' },
  { id: 21, title: 'Artwork 21', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/21.jpg', category: '무우국(國) 미나리(里)의 사계' },
  { id: 22, title: 'Artwork 22', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/22.jpg', category: '무우국(國) 미나리(里)의 사계' },
  { id: 23, title: 'Artwork 23', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/23.jpg', category: '무우국(國) 미나리(里)의 사계' },
  { id: 24, title: 'Artwork 24', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/24.jpg', category: '무우국(國) 미나리(里)의 사계' },
  { id: 25, title: 'Artwork 25', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/25.jpg', category: '무우국(國) 미나리(里)의 사계' },
  { id: 26, title: 'Artwork 26', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/26.jpg', category: '무우국(國) 미나리(里)의 사계' },
  { id: 27, title: 'Artwork 27', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/27.jpg', category: '무우국(國) 미나리(里)의 사계' },
  { id: 28, title: 'Artwork 28', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/28.jpg', category: '무우국(國) 미나리(里)의 사계' },
  { id: 29, title: 'Artwork 29', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/29.jpg', category: '무우국(國) 미나리(里)의 사계' },
  { id: 30, title: 'Artwork 30', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/30.jpg', category: '무우국(國) 미나리(里)의 사계' },
  { id: 31, title: 'Artwork 31', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/31.jpg', category: '무우국(國) 미나리(里)의 사계' },
  { id: 32, title: 'Artwork 32', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/32.jpg', category: '무우국(國) 미나리(里)의 사계' },
  { id: 33, title: 'Artwork 33', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/33.jpg', category: '무우국(國) 미나리(里)의 사계' },
  { id: 34, title: 'Artwork 34', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/34.jpg', category: '무우국(國) 미나리(里)의 사계' },

  // 분류 35-55: 산티아고 순례길 현장 스케치
  { id: 35, title: 'Artwork 35', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/35.jpg', category: '산티아고 순례길 현장 스케치' },
  { id: 36, title: 'Artwork 36', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/36.jpg', category: '산티아고 순례길 현장 스케치' },
  { id: 37, title: 'Artwork 37', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/37.jpg', category: '산티아고 순례길 현장 스케치' },
  { id: 39, title: 'Artwork 39', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/39.jpg', category: '산티아고 순례길 현장 스케치' },
  { id: 40, title: 'Artwork 40', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/40.jpg', category: '산티아고 순례길 현장 스케치' },
  { id: 42, title: 'Artwork 42', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/42.jpg', category: '산티아고 순례길 현장 스케치' },
  { id: 422, title: 'Artwork 42-2', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/42-2.jpg', category: '산티아고 순례길 현장 스케치' },
  { id: 43, title: 'Artwork 43', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/43.jpg', category: '산티아고 순례길 현장 스케치' },
  { id: 45, title: 'Artwork 45', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/45.jpg', category: '산티아고 순례길 현장 스케치' },
  { id: 46, title: 'Artwork 46', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/46.jpg', category: '산티아고 순례길 현장 스케치' },
  { id: 47, title: 'Artwork 47', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/47.jpg', category: '산티아고 순례길 현장 스케치' },
  { id: 48, title: 'Artwork 48', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/48.jpg', category: '산티아고 순례길 현장 스케치' },
  { id: 50, title: 'Artwork 50', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/50.jpg', category: '산티아고 순례길 현장 스케치' },
  { id: 51, title: 'Artwork 51', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/51.jpg', category: '산티아고 순례길 현장 스케치' },
  { id: 52, title: 'Artwork 52', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/52.jpg', category: '산티아고 순례길 현장 스케치' },
  { id: 53, title: 'Artwork 53', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/53.jpg', category: '산티아고 순례길 현장 스케치' },
  { id: 54, title: 'Artwork 54', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/54.jpg', category: '산티아고 순례길 현장 스케치' },
  { id: 55, title: 'Artwork 55', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/55.jpg', category: '산티아고 순례길 현장 스케치' },
  { id: 56, title: 'Artwork 56', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/56.jpg', category: '산티아고 순례길 현장 스케치' },
  { id: 57, title: 'Artwork 57', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/57.jpg', category: '산티아고 순례길 현장 스케치' },
  { id: 58, title: 'Artwork 58', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/58.jpg', category: '산티아고 순례길 현장 스케치' },
  { id: 59, title: 'Artwork 59', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/59.jpg', category: '산티아고 순례길 현장 스케치' },
  { id: 60, title: 'Artwork 60', dimensions: 'TBD', material: '비단에 채색', year: 'TBD', imagePath: '/images/gallery/60.jpg', category: '산티아고 순례길 현장 스케치' },
]

export const categories: string[] = ['전체', ...Array.from(new Set(artworks.map(art => art.category).filter((cat): cat is string => Boolean(cat))))]